/**
 * Runs Sanity TypeGen directly via `@sanity/codegen`, bypassing the
 * `@sanity/cli` bin. The experimental multi-schema/projections build
 * (`@sanity/codegen@*-typegen-experimental.*`) ships inside a v3 `@sanity/cli`,
 * which can't be invoked through its bin in this repo: booting the CLI eagerly
 * loads the v5 `sanity` package's command bridge, which throws a deliberate
 * "cli/studio version mismatch" error. `typegen generate` does no real work
 * itself though — it just reads `sanity-typegen.json` and drives
 * `@sanity/codegen`, so we replicate the worker here. This is a faithful port
 * of `@sanity/cli`'s `workers/typegenGenerate.ts` + `actions/typegen/generateAction.ts`.
 */
import {mkdir, open} from 'node:fs/promises'
import {createRequire} from 'node:module'
import {dirname, join} from 'node:path'
import process from 'node:process'

// Use require, not a top-level `import`: @sanity/codegen's ESM entry
// (exports.import -> lib/index.mjs) is broken — it calls `createRequire(__filename)`,
// and `__filename` is undefined in ESM scope, so a static import throws on load.
// `require` selects the working CJS entry (exports.require -> lib/index.js).
const require = createRequire(import.meta.url)

const {
  DEFAULT_CONFIG,
  readConfig,
  readSchema,
  TypeGenerator,
  findQueriesInPath,
  getResolver,
  registerBabel,
} = require('@sanity/codegen')

const GENERATED_FILE_WARNING = `/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: \`pnpm types:generate\`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 * ---------------------------------------------------------------------------------
 */\n\n`

const DEFAULT_CONFIG_PATH = 'sanity-typegen.json'
const configPath = process.argv[2] ?? DEFAULT_CONFIG_PATH

let config
try {
  config = await readConfig(configPath)
} catch (error) {
  if (error?.code !== 'ENOENT') throw error
  config = DEFAULT_CONFIG
}

const {
  schemas: schemaRefs,
  augmentGroqModule,
  formatGeneratedCode,
  generates,
  overloadClientMethods,
  path: searchPath,
} = config

registerBabel()

const schemas = []
for (const {schemaId, schemaPath} of schemaRefs) {
  schemas.push({schemaId, filename: schemaPath, schema: await readSchema(schemaPath)})
}

const generator = new TypeGenerator({
  schemas,
  queriesByFile: findQueriesInPath({path: searchPath, resolver: getResolver()}),
  augmentGroqModule,
  overloadClientMethods,
})

const outputPath = join(process.cwd(), generates)
await mkdir(dirname(outputPath), {recursive: true})

let fileHandle = await open(outputPath, 'w')
let errorCount = 0
try {
  await fileHandle.write(GENERATED_FILE_WARNING)
  await fileHandle.write(
    [
      generator.getKnownTypes().code,
      ...generator.getSchemaTypeDeclarations().map((i) => i.code),
      generator.getAllSanitySchemaTypesDeclaration().code,
      ...generator.getSchemaDeclarations().map((i) => i.code),
      generator.getAugmentedSchemasDeclarations().code,
    ].join('\n'),
  )

  for await (const {filename, ...result} of generator.getQueryResultDeclarations()) {
    if (result.type === 'error') {
      errorCount += 1
      console.error(
        `Error generating types in "${filename}": ${result.error?.message ?? 'Unknown error'}`,
      )
      continue
    }
    for (const {code} of result.queryResultDeclarations ?? []) {
      await fileHandle.write(code)
    }
  }

  await fileHandle.write((await generator.getAugmentedQueryResultsDeclarations()).code)
  await fileHandle.close()
  fileHandle = null

  if (formatGeneratedCode) {
    const {format} = await import('oxfmt')
    fileHandle = await open(outputPath, 'r+')
    const code = await fileHandle.readFile({encoding: 'utf-8'})
    // Mirror the repo's .oxfmtrc.json so generated types match committed style.
    const {code: formatted, errors} = await format(outputPath, code, {
      bracketSpacing: false,
      printWidth: 100,
      quoteProps: 'consistent',
      semi: false,
      singleQuote: true,
    })
    // oxfmt returns parse/format errors in an array rather than throwing; fail
    // loudly like the previous prettier.format() call did on invalid output.
    if (errors.length > 0) {
      throw new Error(`Failed to format generated types:\n${errors.map(String).join('\n')}`)
    }
    await fileHandle.truncate()
    await fileHandle.write(formatted, 0)
    await fileHandle.close()
    fileHandle = null
  }
} finally {
  await fileHandle?.close()
}

if (errorCount > 0) {
  console.warn(`Generated types to ${generates} with ${errorCount} error(s)`)
} else {
  console.log(`Successfully generated types to ${generates}`)
}
