import {type DocumentOptions, getDocumentState, resolveDocument} from '@sanity/sdk'
import {type SanityDocument} from '@sanity/types'

import {type DocumentHandle} from '../../config/handles'
import {createStateSourceHook} from '../helpers/createStateSourceHook'
import {useNormalizedResourceOptions} from '../helpers/useNormalizedResourceOptions'
// used in an `{@link useDocumentProjection}` and `{@link useQuery}`
// eslint-disable-next-line import/consistent-type-specifier-style, unused-imports/no-unused-imports
import type {useDocumentProjection} from '../projection/useDocumentProjection'
// eslint-disable-next-line import/consistent-type-specifier-style, unused-imports/no-unused-imports
import type {useQuery} from '../query/useQuery'

const useDocumentValue = createStateSourceHook({
  // Pass options directly to getDocumentState
  getState: (instance, options: DocumentOptions<string | undefined>) =>
    getDocumentState(instance, options),
  // Pass options directly to getDocumentState for checking current value
  shouldSuspend: (instance, {path: _path, ...options}: DocumentOptions<string | undefined>) =>
    getDocumentState(instance, options).getCurrent() === undefined,
  // Extract handle part for resolveDocument
  suspender: (instance, options: DocumentOptions<string | undefined>) =>
    resolveDocument(instance, options),
})

const wrapHookWithData = <TParams extends unknown[], TReturn>(
  useValue: (...params: TParams) => TReturn,
) => {
  function useHook(...params: TParams) {
    return {data: useValue(...params)}
  }
  return useHook
}

type UseDocumentOptions<
  TPath extends string | undefined = undefined,
  TDocumentType extends string = string,
  TDataset extends string = string,
  TProjectId extends string = string,
> = DocumentHandle<TDocumentType, TDataset, TProjectId> & {path?: TPath}

interface UseDocument {
  /**
   * @public
   *
   * ## useDocument with Explicit Types (no path)
   *
   * Provide an explicit type parameter `TData` to type the returned document data.
   * You can define your own interfaces or use types generated by your Sanity Studio.
   *
   * This hook will suspend while the document data is being fetched.
   *
   * @typeParam TData - The explicit type for the document
   * @param options - Configuration including `documentId`, `documentType`, and optionally:
   *   - `projectId`/`dataset`: For multi-project/dataset setups
   * @returns The document state
   *
   * @example Basic document fetch with explicit type
   * ```tsx
   * import {useDocument, type DocumentHandle, type SanityDocument} from '@sanity/sdk-react'
   *
   * interface Book extends SanityDocument {
   *   _type: 'book'
   *   title: string
   *   author: string
   * }
   *
   * interface BookViewProps {
   *   doc: DocumentHandle
   * }
   *
   * function BookView({doc}: BookViewProps) {
   *   const {data: book} = useDocument<Book>({...doc})
   *   return <h1>{book?.title ?? 'Untitled'} by {book?.author ?? 'Unknown'}</h1>
   * }
   * ```
   *
   * @inlineType DocumentOptions
   */
  <TData>(options: UseDocumentOptions<undefined>): {data: TData | null}

  /**
   * @public
   *
   * ## useDocument with Explicit Types (with path)
   *
   * Provide an explicit type parameter `TData` to type the returned field data
   * when using a `path` to select a nested value.
   *
   * @typeParam TData - The explicit type for the field
   * @param options - Configuration including `documentId`, `documentType`, `path`, and optionally:
   *   - `projectId`/`dataset`: For multi-project/dataset setups
   * @returns The field value at the specified path
   *
   * @example Fetching a specific field with explicit type
   * ```tsx
   * import {useDocument, type DocumentHandle} from '@sanity/sdk-react'
   *
   * function BookTitle({doc}: {doc: DocumentHandle}) {
   *   const {data: title} = useDocument<string>({...doc, path: 'title'})
   *   return <h1>{title ?? 'Untitled'}</h1>
   * }
   * ```
   *
   * @inlineType DocumentOptions
   */
  <TData>(options: UseDocumentOptions<string>): {data: TData | undefined}

  /**
   * @public
   *
   * ## useDocument (default)
   *
   * When no explicit type parameter is provided, the hook returns `SanityDocument`.
   *
   * This hook will suspend while the document data is being fetched and loaded.
   *
   * When fetching a full document:
   * - Returns the complete document object if it exists
   * - Returns `null` if the document doesn't exist
   *
   * When fetching with a path:
   * - Returns the value at the specified path if both the document and path exist
   * - Returns `undefined` if either the document doesn't exist or the path doesn't exist in the document
   *
   * @category Documents
   * @param options - Configuration including `documentId`, `documentType`, and optionally:
   *   - `path`: To select a nested value
   *   - `projectId`/`dataset`: For multi-project/dataset setups
   * @returns The document state (or nested value if path provided).
   *
   * @example Basic document fetch
   * ```tsx
   * import {useDocument, type DocumentHandle} from '@sanity/sdk-react'
   *
   * function ProductView({doc}: {doc: DocumentHandle}) {
   *   const {data: product} = useDocument({...doc})
   *   return <h1>{product?.title ?? 'Untitled'}</h1>
   * }
   * ```
   *
   * @inlineType DocumentOptions
   */
  (options: UseDocumentOptions<undefined>): {data: SanityDocument | null}

  /**
   * @internal
   */
  (options: UseDocumentOptions): {data: unknown}
}

/**
 * @public
 * Reads and subscribes to a document's realtime state, incorporating both local and remote changes.
 *
 * You can provide an explicit type parameter for full type safety:
 * - `useDocument<MyType>({...})` returns `{data: MyType | null}`
 * - `useDocument<string>({..., path: 'title'})` returns `{data: string | undefined}`
 *
 * Without a type parameter, data is typed as `SanityDocument`.
 *
 * @remarks
 * `useDocument` is ideal for realtime editing interfaces where you need immediate feedback on changes.
 * However, it can be resource-intensive since it maintains a realtime connection.
 *
 * For simpler cases where:
 * - You only need to display content
 * - Realtime updates aren't critical
 * - You want better performance
 *
 * …consider using {@link useDocumentProjection} or {@link useQuery} instead. These hooks are more efficient
 * for read-heavy applications.
 *
 * @function
 */
export const useDocument = wrapHookWithData((options: UseDocumentOptions) => {
  const normalizedOptions = useNormalizedResourceOptions(options)
  return useDocumentValue(normalizedOptions)
}) as UseDocument
