/* eslint-disable no-console -- a build step; its console output is the failure report */
/**
 * Fails the build if the typegen module augmentations are not reachable from the entry
 * declaration.
 *
 * The compatibility shim reaches consumers only as `declare module` blocks, pulled in by
 * side-effect imports in `src/typegen/resolve.ts`. A bundler that tree-shook those
 * imports, or that emitted the blocks into a chunk nothing references, would break every
 * app whose `sanity.types.ts` came from the experimental flow while typecheck, tests and
 * `tsconfig.shimcheck.json` all stayed green.
 *
 * Presence in `dist` is not enough: a block in an unreferenced chunk is inert for
 * consumers. So this walks the relative-import closure starting at the file
 * the package's entry declaration points at, which is what a consumer's TypeScript
 * actually loads.
 *
 * Delete alongside src/typegen/ once the augmentations move to `@sanity/client` and
 * `groq` themselves.
 */
import {readFile} from 'node:fs/promises'
import {dirname, resolve} from 'node:path'
import process from 'node:process'
import {fileURLToPath} from 'node:url'

const PKG_DIR = fileURLToPath(new URL('../', import.meta.url))
// Anchored to line start on purpose: the `@example` blocks in clientAugmentation.ts
// emit the same text indented as ` * declare module '@sanity/client' {`, and a substring
// match would be satisfied by the comment alone while the real block was missing.
const REQUIRED = [
  {label: "declare module 'groq'", pattern: /^declare module 'groq'/m},
  {label: "declare module '@sanity/client'", pattern: /^declare module '@sanity\/client'/m},
]

const pkg = JSON.parse(await readFile(resolve(PKG_DIR, 'package.json'), 'utf8'))
// The exports map carries no `types` condition here, so TypeScript falls back to the
// top-level `types` field. Prefer the condition if one is ever added.
const entry = pkg.exports?.['.']?.types ?? pkg.types
if (!entry) throw new Error('package.json declares no entry declaration file')

/** Rewrites a relative specifier to the declaration file it resolves to. */
const toDeclaration = (spec, fromDir) =>
  resolve(fromDir, spec.replace(/\.js$/, '.d.ts').replace(/^(\.\.?\/[^.]*)$/, '$1.d.ts'))

const seen = new Set()
const queue = [resolve(PKG_DIR, entry)]
const closure = []

while (queue.length > 0) {
  const file = queue.pop()
  if (seen.has(file)) continue
  seen.add(file)

  let source
  try {
    source = await readFile(file, 'utf8')
  } catch {
    continue // a specifier that does not resolve to a declaration file on disk
  }
  closure.push(source)

  for (const [, spec] of source.matchAll(/from\s+["'](\.[^"']+)["']/g)) {
    queue.push(toDeclaration(spec, dirname(file)))
  }
}

const combined = closure.join('\n')
const missing = REQUIRED.filter(({pattern}) => !pattern.test(combined)).map((r) => r.label)

if (missing.length > 0) {
  console.error(
    `Not reachable from ${entry}: ${missing.join(', ')}.\n` +
      `Walked ${seen.size} declaration files. The typegen augmentations must ship and be ` +
      `reachable from the entry, or apps generated by the experimental flow stop typechecking.`,
  )
  process.exit(1)
}

console.log(`Typegen augmentations reachable from ${entry} (${closure.length} files walked).`)
