/**
 * Fails the build if the typegen module augmentations did not survive into `dist`.
 *
 * The compatibility shim reaches consumers only as `declare module` blocks inside the
 * emitted declarations, pulled in by side-effect imports in `src/typegen/resolve.ts`. A
 * bundler that tree-shakes those imports would drop the blocks and break every app whose
 * `sanity.types.ts` came from the experimental flow, while typecheck, tests and
 * `tsconfig.shimcheck.json` all stayed green. Nothing else in the repo looks at built
 * output.
 *
 * Delete alongside src/typegen/ once the augmentations move to `@sanity/client` and
 * `groq` themselves.
 */
/* eslint-disable no-console -- a build step; its console output is the failure report */
import {readdir, readFile} from 'node:fs/promises'
import {join} from 'node:path'
import process from 'node:process'

const DIST = new URL('../dist/', import.meta.url).pathname
const REQUIRED = ["declare module 'groq'", "declare module '@sanity/client'"]

const files = (await readdir(DIST)).filter((f) => f.endsWith('.d.ts'))
if (files.length === 0) throw new Error(`No .d.ts files in ${DIST}; did the build run?`)

const contents = await Promise.all(files.map((f) => readFile(join(DIST, f), 'utf8')))
const combined = contents.join('\n')
const missing = REQUIRED.filter((needle) => !combined.includes(needle))

if (missing.length > 0) {
  console.error(
    `Missing from the built declarations: ${missing.join(', ')}.\n` +
      `Checked ${files.length} .d.ts files in dist/. The typegen augmentations must ship, ` +
      `or apps generated by the experimental flow stop typechecking.`,
  )
  process.exit(1)
}

console.log(`Typegen augmentations present in dist (${REQUIRED.length}/${REQUIRED.length}).`)
