// auto-generated by sanity CLI — do not edit
import type {DocumentResource} from '@sanity/sdk'

declare module '@sanity/sdk' {
  interface RegisteredResources {
    default: true
    secondary: true
  }
}

export const resources = {
  default: {projectId: 'ppsg7ml5', dataset: 'test'},
  secondary: {projectId: 'vo1ysemo', dataset: 'production'},
} satisfies Record<string, DocumentResource>
