import './clientAugmentation'
import './groqCompat'

import {
  type SanityProjectionsByResource,
  type SanityQueries,
  type SanityQueriesByResource,
  type SanitySchemasByResource,
} from '@sanity/client'
import {
  type SanityDocument as LegacySanityDocument,
  type SanityProjectionResult as LegacySanityProjectionResult,
  type SanityQueryResult as LegacySanityQueryResult,
} from 'groq'

/**
 * Falls back to `TFallback` when `T` is `never`, which is what both key spaces yield for
 * a key they do not carry. The tuple wrapper tests a union `T` as a whole rather than
 * distributing over it.
 */
type Or<T, TFallback> = [T] extends [never] ? TFallback : T

/** Indexes `T` by `TKey`, yielding `never` rather than an error when the key is absent. */
type At<T, TKey extends string> = TKey extends keyof T ? T[TKey] : never

/**
 * Fields Sanity adds to every document. A resource's key space holds every type in its
 * schema, objects included, so {@link ResolveDocument} filters by these.
 */
type DocumentFields = {
  _id: string
  _type: string
  _createdAt: string
  _updatedAt: string
  _rev: string
  // Keeps the filtered type assignable to `DocumentSet`, which requires an index
  // signature. Typegen emits document types as aliases, so they carry an implicit one.
  [key: string]: unknown
}

/**
 * Resolves a document type from the resource-keyed interfaces on `@sanity/client`,
 * falling back to the legacy `groq` key space so files generated by the experimental
 * Typegen flow keep resolving. An unregistered `_type` resolves to `never`; an
 * unconstrained lookup resolves to the base document shape.
 *
 * @beta
 */
export type ResolveDocument<
  TDocumentType extends string = string,
  TResourceKey extends string = string,
> = Or<
  Extract<At<SanitySchemasByResource, TResourceKey>, DocumentFields & {_type: TDocumentType}>,
  LegacySanityDocument<TDocumentType, TResourceKey>
>

/**
 * Resolves a query result from the resource-keyed interfaces on `@sanity/client`,
 * falling back to that module's flat `SanityQueries`, which is what
 * `sanity typegen generate` emits, and then to the legacy `groq` key space.
 *
 * The flat space carries no resource, so a query registered there resolves the same way
 * for every handle. It is still tried before the legacy space, because the legacy lookup
 * matches loosely: {@link SafeAccess} falls back to the union of every registered value
 * when a key is absent, so it would answer for a query it does not carry. An app holding
 * both a legacy file and a generated one needs the exact lookup to win.
 *
 * @beta
 */
export type ResolveQueryResult<
  TQuery extends string = string,
  TResourceKey extends string = string,
> = Or<
  At<At<SanityQueriesByResource, TResourceKey>, TQuery>,
  Or<At<SanityQueries, TQuery>, LegacySanityQueryResult<TQuery, TResourceKey>>
>

/**
 * Resolves a projection result from the resource-keyed interfaces on `@sanity/client`,
 * falling back to the legacy `groq` key space. Narrows by document type as well as by
 * resource, because one projection is evaluated against every document type in a schema.
 *
 * @beta
 */
export type ResolveProjectionResult<
  TProjection extends string = string,
  TDocumentType extends string = string,
  TResourceKey extends string = string,
> = Or<
  Extract<
    At<At<At<SanityProjectionsByResource, TResourceKey>, TProjection>, TDocumentType>,
    object
  >,
  LegacySanityProjectionResult<TProjection, TDocumentType, TResourceKey>
>
