name: Bundle Stats

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  bundle-stats:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 24

      - name: Bundle Stats
        uses: rexxars/bundle-stats@5b965c0d5954a27d44a7def1f8293ef677e1ecd4 # v1.9.3
        with:
          packages: "packages/core,packages/react"
          build-command: "pnpm turbo run build --filter=@sanity/sdk... --filter=@sanity/sdk-react..."
          compare-npm: "latest"
