name: Bundle Stats

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  bundle-stats:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 24

      - name: Bundle Stats
        uses: rexxars/bundle-stats@4154b0052bf95b435cc3829fe90cd06a2f9d4dcd # v1.9.1
        with:
          packages: 'packages/core,packages/react'
          build-command: 'pnpm turbo run build --filter=@sanity/sdk... --filter=@sanity/sdk-react...'
          compare-npm: 'latest'
