name: Depcheck

on:
  # Build on pushes to branches that have a PR (including drafts)
  pull_request:
  # Build on pushes to the main branch
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depcheck:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Depcheck
        run: pnpm depcheck
        env:
          CI: true
          SDK_E2E_USER_ID: ${{ secrets.SDK_E2E_USER_ID }}
          SDK_E2E_USER_PASSWORD: ${{ secrets.SDK_E2E_USER_PASSWORD }}
          RECAPTCHA_E2E_STAGING_KEY: ${{ secrets.RECAPTCHA_E2E_STAGING_KEY }}
