name: Post Release Notes to Slack

on:
  release:
    types: [published] # triggers only when a new release is published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Convert markdown to slack markdown
        uses: LoveToKnow/slackify-markdown-action@698a1d4d0ff1794152a93c03ee8ca5e03a310d4e # v1.1.1
        id: releasemarkdown
        with:
          text: "## Notes:\n${{ github.event.release.body }}"
      - name: Send release notes to Slack
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            icon_emoji: "ship-it-pirate"
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "New SDK Release Published!"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Name:*\n${{ github.event.release.name }}"
              - type: section
                text:
                  type: mrkdwn
                  text: ${{toJson(steps.releasemarkdown.outputs.text)}}
  mark-issues-as-done:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Mark SDK issues as done
        uses: sanity-io/mark-issues-done-action@main
        with:
          linear_api_key: ${{secrets.LINEAR_API_TOKEN}}
          repository_name: ${{github.event.repository.name}}
          # Label: In Staging
          initial_state_id: "c56956cd-c281-4ca5-889f-6189ce231a6d"
          # Label: Shipped
          done_state_id: "5a35b7bf-6d37-4cc2-854a-2f18d160e2e5"
