name: Release Please
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.DOCS_VERCEL_PRODUCTION_PROJECT_ID }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to NPM
        required: true
        default: false
        type: boolean

permissions:
  contents: read # for checkout

jobs:
  release-please:
    outputs:
      command: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        id: generate-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      # This action will create a release PR when regular conventional commits are pushed to main, it'll also detect if a release PR is merged and npm publish should happen
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # Publish to NPM on new releases
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        with:
          cache: pnpm
          node-version: lts/*
      - name: install deps & build
        run: pnpm install --ignore-scripts && pnpm build --filter=!./apps/*
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      # Release Please has already incremented versions and published tags, so we just
      # need to publish all unpublished versions to NPM here
      - run: pnpm publish -r --filter=!./apps/*
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        env:
          NPM_CONFIG_PROVENANCE: true

  post-release-steps:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.command == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Docs to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Mark SDK issues as done
        uses: sanity-labs/mark-issues-done-action@88e6a3e6bc5a9c86d45873c4dba3302a4cafcb65 # main
        with:
          linear_api_key: ${{secrets.LINEAR_API_TOKEN}}
          repository_name: ${{github.event.repository.name}}
          # Label: In Staging
          initial_state_id: "c56956cd-c281-4ca5-889f-6189ce231a6d"
          # Label: Shipped
          done_state_id: "5a35b7bf-6d37-4cc2-854a-2f18d160e2e5"

      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@a81cd720792a6088debd7f182b552845abb86f1b # v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
