name: Test

on:
  # Build on pushes to branches that have a PR (including drafts)
  pull_request:
  # Build on pushes to the main branch
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Test
        run: pnpm test --test-timeout=60000 --retry 4 --coverage --reporter=default --reporter=blob

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: blob-report-${{ github.run_id }}-22
          path: ".vitest-reports/*"
          include-hidden-files: true
          retention-days: 1

  test-compat:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Test (Node 20 compatibility)
        run: pnpm test --test-timeout=60000 --retry 1

  report-coverage:
    if: ${{ !cancelled() }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: "Download coverage artifacts"
        uses: actions/download-artifact@v7
        with:
          path: .vitest-reports
          pattern: blob-report-${{ github.run_id }}-*
          merge-multiple: true

      - name: Merged report
        run: |
          pnpm vitest run --merge-reports --coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2
